# .github/workflows/sonar.yml
name: Sonar Scan

on:
 workflow_call:

jobs:
  sonar:
    runs-on: self-hosted
    #needs: build  # Ensures Sonar runs after build succeeds
    steps:
      - name: SonarCloud Scan
        run: mvn sonar:sonar -Dsonar.projectKey=gayathriarun001_DevSecops -Dsonar.organization=gayathriarun001 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=146265dcce48e7bcf0c43ba0662b3ae9708bc538
        
